<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'index'),
            'default',
            true) ?>">Logout</a>
    </div>
</div>
<br /><br />
<div id="view-content">
	<p>View script for controller <b>Login</b> and script/action name <b>productregistersucess</b></p>
</div>
<?php
$this->form->setAction($this->url());
echo $this->form;